#!/usr/bin/env zsh

### Installs zsh Git completion if not present
if [ -d "$(brew --prefix)/share/zsh-completions" ]; then
  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi
else
  echo "run: brew install git zsh-completion"
fi

# Zsh Prompt
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '(%b)'

setopt PROMPT_SUBST

# Dynamic values must be in single quote for some reasonhttps://stackoverflow.com/a/11877873
local ruby_version='$RUBY_VERSION'
local current_dir='$PWD'
local git='${vcs_info_msg_0_}'

local bright_blue="033" # https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-ps1-prompt/124409#124409
# display <chruby version> <pwd> (git_branch)
# $
export PROMPT="⛄️ %F{$bright_blue}${ruby_version}%F{none} 🚀 ${current_dir} %F{red}${git}%F{none}"$'\n'"\$ "

# Set tab value to current folder name
export PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007"';

